{{ if .Values.DemoLetsEncryptClusterIssuer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certmanager-issuer.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "certmanager-issuer.labels" . | nindent 4 }}
data:
  create-issuer: |
{{ include (print $.Template.BasePath "/_create_issuer.sh") . | indent 4 }}
  issuer.yml: |
{{ include (print $.Template.BasePath "/_issuer.yaml") . | indent 4 }}
{{ end }}
