{{ if .Values.DemoLetsEncryptClusterIssuer.enabled }} 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certmanager-issuer.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "certmanager-issuer.labels" . | nindent 4 }}
  annotations:
    namespace: {{ .Values.global.namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "certmanager-issuer.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "certmanager-issuer.labels" . | nindent 4 }}
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["issuers"]
  verbs: ["get", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "certmanager-issuer.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "certmanager-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "certmanager-issuer.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "certmanager-issuer.fullname" . }}
    namespace: {{ .Values.global.namespace }}
{{ end }}